"""add_otp_fields_to_customers

Revision ID: 324e721e1eec
Revises: 44e10796df7f
Create Date: 2026-01-20 15:11:04.847428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324e721e1eec'
down_revision: Union[str, None] = '44e10796df7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('otp_code', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'otp_expires_at')
    op.drop_column('customers', 'otp_code')
    # ### end Alembic commands ###
