"""add age to users

Revision ID: 80dd0c737e8c
Revises: 8d71a0775e3f
Create Date: 2026-01-29 06:54:26.796398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dd0c737e8c'
down_revision: Union[str, None] = '8d71a0775e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'password_hash')
    # ### end Alembic commands ###
